"""
Regenerate script transliterations for the test split using the TULIP chat endpoint
(different model from the Qwen3/code endpoint used for training data).

This breaks the circular evaluation problem: training data was generated by the
code/Qwen3 endpoint; this script uses the chat endpoint (gpt-oss reasoning model)
for test-split transliterations only.

Usage:
    python src/llm_generator_pipeline/05_regen_test_independent.py \
        --dataset data/pipeline/04_dataset.jsonl \
        --output  data/pipeline/05_test_independent.jsonl

Output format: same schema as 04_dataset.jsonl, test split only.
  - phonetic positives: kept as-is from original (Latin variants, same model is fine)
  - script/combined positives from wikidata: kept as-is
  - script/combined positives from llm: REPLACED with fresh chat-model transliterations
"""
from __future__ import annotations

import argparse
import json
import os
import concurrent.futures
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI
from tqdm.auto import tqdm

load_dotenv()

CHAT_BASE_URL = "https://api.tulip.tudelft.nl/chat/v1/"
TARGET_SCRIPTS = ["ar", "ru", "zh", "ja", "he", "hi", "el", "ko"]
MAX_WORKERS = 50
MAX_TOKENS = 4096


def _get_client() -> OpenAI:
    return OpenAI(
        base_url=CHAT_BASE_URL,
        api_key=os.environ["TUDELFT_TULIP_API_KEY"],
    )


def transliterate_name(name: str, client: OpenAI) -> dict[str, str]:
    """Transliterate a single name into all 8 target scripts via chat endpoint."""
    prompt = (
        f'Transliterate the person name "{name}" into the following scripts. '
        f'Return ONLY a JSON object with these exact keys, no explanation:\n'
        f'{{"ar": "", "ru": "", "zh": "", "ja": "", "he": "", "hi": "", "el": "", "ko": ""}}'
    )
    try:
        r = client.chat.completions.create(
            model="chat",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=MAX_TOKENS,
        )
        content = r.choices[0].message.content
        if content:
            parsed = json.loads(content)
            # ensure all scripts present
            return {s: parsed.get(s, "") for s in TARGET_SCRIPTS}
        else:
            print(f"[WARN] empty content for {name!r}, finish={r.choices[0].finish_reason}")
    except Exception as e:
        print(f"[ERROR] transliterate_name({name!r}): {type(e).__name__}: {e}")
        raise  # re-raise so ThreadPoolExecutor captures it in the future
    return {s: "" for s in TARGET_SCRIPTS}


def to_bytes(text: str) -> list[int]:
    return list(text.encode("utf-8"))


def build_new_record(original: dict, fresh_variants: dict[str, dict[str, str]]) -> dict:
    """
    Rebuild a test record replacing llm script/combined positives with fresh ones.
    fresh_variants: {name -> {script_code -> transliterated_text}}
    """
    new_positives = []

    # Keep phonetic (Latin) positives unchanged — same model is fine, these are
    # Latin→Latin variants and the circular eval concern is about cross-script only.
    for p in original["positives"]:
        if p["type"] == "phonetic":
            new_positives.append(p)

    # Keep wikidata-sourced positives unchanged — they're human-curated.
    for p in original["positives"]:
        if p["source"] == "wikidata":
            new_positives.append(p)

    # Build fresh script/combined positives from chat-model transliterations.
    anchor_text = original["anchor"]["text"]
    # Determine which names were transliterated for this entity.
    # anchor_text → type=script; latin variants → type=combined
    original_latin_variants = [
        p["text"] for p in original["positives"] if p["type"] == "phonetic"
    ]

    for name, script_map in fresh_variants.items():
        pair_type = "script" if name == anchor_text else "combined"
        for script_code, text in script_map.items():
            if not text:
                continue
            new_positives.append({
                "text": text,
                "bytes": to_bytes(text),
                "type": pair_type,
                "script": script_code,
                "source": "llm_chat",
            })

    # Deduplicate by text (case-insensitive), prefer wikidata > llm_chat > llm
    source_priority = {"wikidata": 0, "llm_chat": 1, "llm": 2}
    seen: dict[str, int] = {}  # text_key -> index in deduped
    deduped = []
    for p in new_positives:
        key = p["text"].strip().lower()
        if key not in seen:
            deduped.append(p)
            seen[key] = len(deduped) - 1
        else:
            existing = deduped[seen[key]]
            if source_priority.get(p["source"], 9) < source_priority.get(existing["source"], 9):
                deduped[seen[key]] = p

    return {
        "entity_id": original["entity_id"],
        "split": original["split"],
        "anchor": original["anchor"],
        "positives": deduped,
    }


def load_processed_ids(output_path: str) -> set[str]:
    """Only count records that have at least one llm_chat positive as truly done."""
    processed = set()
    try:
        with open(output_path, encoding="utf-8") as f:
            for line in f:
                r = json.loads(line)
                if any(p["source"] == "llm_chat" for p in r["positives"]):
                    processed.add(r["entity_id"])
    except FileNotFoundError:
        pass
    return processed


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset",   default="data/pipeline/04_dataset.jsonl")
    parser.add_argument("--output",    default="data/pipeline/05_test_independent.jsonl")
    parser.add_argument("--workers",   type=int, default=MAX_WORKERS)
    parser.add_argument("--shard",     type=int, default=0)
    parser.add_argument("--n_shards",  type=int, default=1)
    args = parser.parse_args()

    # Load test records
    test_records = []
    with open(args.dataset, encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            if r["split"] == "test":
                test_records.append(r)
    print(f"Test records: {len(test_records)}")

    processed_ids = load_processed_ids(args.output)
    remaining = [r for r in test_records if r["entity_id"] not in processed_ids]
    remaining = remaining[args.shard::args.n_shards]
    print(f"Already done (with llm_chat positives): {len(processed_ids)} | Remaining this shard: {len(remaining)}")

    if not remaining:
        print("All records already processed.")
        return

    # Load already-valid records so we can rewrite the file cleanly
    valid_records: dict[str, dict] = {}
    try:
        with open(args.output, encoding="utf-8") as f:
            for line in f:
                r = json.loads(line)
                if r["entity_id"] in processed_ids:
                    valid_records[r["entity_id"]] = r
    except FileNotFoundError:
        pass

    client = _get_client()

    # Build flat (record_idx, name) job list
    # For each entity: transliterate anchor + all latin variants
    jobs: list[tuple[int, str]] = []
    for i, record in enumerate(remaining):
        anchor = record["anchor"]["text"]
        latin_variants = [p["text"] for p in record["positives"] if p["type"] == "phonetic"]
        for name in [anchor] + latin_variants:
            jobs.append((i, name))

    print(f"Total transliteration jobs: {len(jobs)}")

    # Collect results per record
    fresh_variants: list[dict[str, dict[str, str]]] = [{} for _ in remaining]
    pending: dict[int, int] = {}
    for i, name in jobs:
        pending[i] = pending.get(i, 0) + 1

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)

    new_records: dict[str, dict] = {}

    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as ex:
        future_to_job = {
            ex.submit(transliterate_name, name, client): (i, name)
            for i, name in jobs
        }
        for fut in tqdm(
            concurrent.futures.as_completed(future_to_job),
            total=len(jobs),
            desc="Transliterating",
        ):
            i, name = future_to_job[fut]
            try:
                fresh_variants[i][name] = fut.result()
            except Exception as e:
                print(f"[SKIP] {name!r}: {e}")
                fresh_variants[i][name] = {s: "" for s in TARGET_SCRIPTS}
            pending[i] -= 1

            if pending[i] == 0:
                new_record = build_new_record(remaining[i], fresh_variants[i])
                new_records[new_record["entity_id"]] = new_record

    # Rewrite output: valid previously-done records + newly completed records
    all_output = {**valid_records, **new_records}
    with open(args.output, "w", encoding="utf-8") as out:
        for eid in [r["entity_id"] for r in test_records]:
            if eid in all_output:
                out.write(json.dumps(all_output[eid], ensure_ascii=False) + "\n")

    done = sum(1 for r in all_output.values() if any(p["source"] == "llm_chat" for p in r["positives"]))
    print(f"Done. {done}/{len(test_records)} records with llm_chat positives. Output: {args.output}")


if __name__ == "__main__":
    main()
